Repository dequelabs/axe-core, pull requests merged in 2018-08, with the labels that each got.

#1061 fix(meta-viewport): show attribute in message
  lib/checks/mobile/meta-viewport-scale.js
  lib/checks/mobile/meta-viewport.json
  test/checks/mobile/meta-viewport-scale.js
Labels: Support

#945 feat(rule): aria-allowed-role
  doc/rule-descriptions.md
  lib/checks/aria/aria-allowed-role.js
  lib/checks/aria/aria-allowed-role.json
  lib/commons/aria/get-element-unallowed-roles.js
  lib/commons/aria/index.js
  lib/commons/aria/is-aria-role-allowed-on-element.js
  lib/commons/aria/roles.js
  lib/commons/aria/validate-node-and-attributes.js
  lib/commons/utils/is-html-element.js
  lib/rules/aria-allowed-role.json
  test/checks/aria/aria-allowed-role.js
  test/commons/aria/get-element-unallowed-roles.js
  test/commons/aria/is-aria-role-allowed-on-element.js
  test/commons/aria/validate-node-and-attributes.js
  test/commons/utils/is-html-element.js
  test/integration/rules/aria-allowed-role/aria-allowed-role.html
  test/integration/rules/aria-allowed-role/aria-allowed-role.json
Labels: rules

#1106 Release v3.1.1
  CHANGELOG.md
  bower.json
  circle.yml
  doc/examples/chrome-debugging-protocol/package.json
  doc/examples/jasmine/package.json
  doc/examples/jest_react/package.json
  doc/examples/mocha/package.json
  doc/examples/phantomjs/package.json
  doc/examples/puppeteer/package.json
  doc/examples/qunit/package.json
  package.json
  sri-history.json
Labels: release
